### ISSUE TITLE
wrong pageflow.height on Android because of the status bar

### ISSUE THREAD

**Issue by vdesdoigts** [jolicode/Badass-Pageflow#8]
On Android you have to subtract 25dpi on the pageflow.height because of the status bar.
Otherwise the bottom content is hidden.

**Comment by xavierlacot** [comment]
This is indeed not a bug in the widget, it is a configuration directive given to the widget which has to be changed. Moreover, I guess the widget sizes should rather be configured on a per-instance basis, instead of the global use of `Alloy.Globals.jolicode.pageflow.width` or `Alloy.Globals.jolicode.pageflow.height`.
